vich_uploader:
    db_driver: orm

    mappings:
        post_images:
            uri_prefix: /divers/images
            upload_destination: '%kernel.project_dir%/public/divers/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
