# Paramètres globaux pour l'application
parameters:
    app.jwtsecret: '%env(APP_JWTSECRET)%'
    upload_directory: '%kernel.project_dir%/public/divers/images'

services:
    # Définition explicite de JWTService
    App\Service\JWTService:
        arguments:
            $jwtSecret: '%app.jwtsecret%'



    # Configuration par défaut des services
    _defaults:
        autowire: true      
        autoconfigure: true  

    # Déclare automatiquement tous les services du dossier src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
